replicaCount: 2

image:
  repository: zotovkem86/car-otus
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: NodePort
  port: 9000
  targetPort: 8083

ingress:
  enabled: true
  hosts:
    - host: carapp
      paths: ["/app"]

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: car-otus
  service:
    port: "5432"
  persistence:
    size: 1Gi

metrics:
  serviceMonitor:
    enabled: true
