apiVersion: v2
name: carapp
description: Lab 2 Otus CRUD app car

type: application

version: 0.1.0

appVersion: "V1"
dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - carapp-database
