replicaCount: 2

image:
  repository: zotovkem86/car-otus:v1
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: NodePort
  port: 80
  targetPort: 8083

ingress:
  enabled: false
  hosts:
    - host: arch.howework
      paths:
        - path: /
          backend:
            serviceName: car-otus
            servicePort: 8083
postgresql:
  nameOverride: postgres
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: carapp
  service:
    port: "5432"
