apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: order-otus
      context: .
deploy:
  helm:
    releases:
      - name: orderapp
        chartPath: orderapp
        skipBuildDependencies: true
