build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-pod
profiles:
  - name: profile1
    activation:
      - kubeContext: minikube
        command: dev
