{
 "title": "ZotovLab3Prom",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "nginx-ingress-controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{host=\"carapp\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency 0.9",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le,uri) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"carapp\"}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, max by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"carapp\"}[2m]))) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le,uri) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"carapp\"}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,uri) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"carapp\"}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Errors500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{host=\"carapp\", status=~\"5.+\"}[2m]))"
    }
   ]
  },
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/cars\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency 0.9",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le,uri) (rate(http_server_requests_seconds_bucket{uri=\"/cars\"}[2m]))) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, max by (le) (rate(http_server_requests_seconds_bucket{uri=\"/cars\"}[2m]))) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le,uri) (rate(http_server_requests_seconds_bucket{uri=\"/cars\"}[2m]))) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,uri) (rate(http_server_requests_seconds_bucket{uri=\"/cars\"}[2m]))) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Errors500",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/cars\", status=~\"5.+\"}[2m]))"
    }
   ]
  }
 ]
}